#应用程序名称和启动端口号
spring:
  application:
    name: eureka-client-demo
server:
  port: 8080

#eureka注册中心
eureka:
  client:
    service-url:
      default-Zone: http://eureka1:8761，http://eureka2:8762，http://eureka3:8763，
  instance:
    hostname: client-demo-yyy
    appname: client-demo-xxx